/*
 * @Author: Salt
 * @Date: 2023-07-23 13:25:47
 * @LastEditors: Salt
 * @LastEditTime: 2023-07-23 17:44:20
 * @Description: 插件入口文件
 * @FilePath: \SaltFun\app\src\main\java\salt\saltfun\Saltfun.java
 */
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package salt.saltfun;

import org.bukkit.plugin.java.JavaPlugin;


public class Saltfun extends JavaPlugin {

    private static Saltfun instance;
    /** 获取实例 */
    public static Saltfun getInstance() {
        return instance;
    }

    @Override
    public void onEnable() {
        instance = this;
    }
}
